export const sizeText = {
  'heading-web-1': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '80px',
    lineHeight: '88px',
    letterSpacing: '-0.02em',
  },
  'heading-web-2': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '56px',
    lineHeight: '64px',
    letterSpacing: '-0.02em',
  },
  'heading-web-3': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '40px',
    lineHeight: '44px',
    letterSpacing: '-0.02em',
  },
  'heading-web-4': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '32px',
    lineHeight: '36px',
    letterSpacing: '-0.02em',
  },
  'heading-web-5': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '24px',
    lineHeight: '28px',
    letterSpacing: '-0.02em',
  },
  'heading-web-6': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '20px',
    lineHeight: '24px',
    letterSpacing: '-0.02em',
  },

  'heading-mobile-1': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '44px',
    lineHeight: '48px',
    letterSpacing: '-0.012em',
  },
  'heading-mobile-2': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '32px',
    lineHeight: '36px',
    letterSpacing: '-0.012em',
  },
  'heading-mobile-3': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '24px',
    lineHeight: '28px',
    letterSpacing: '-0.012em',
  },
  'heading-mobile-4': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '20px',
    lineHeight: '24px',
    letterSpacing: '-0.012em',
  },
  'heading-mobile-5': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '20px',
    letterSpacing: '-0.012em',
  },
  'heading-mobile-6': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '18px',
    letterSpacing: '-0.012em',
  },

  'paragraph-xxl-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '32px',
    lineHeight: '48px',
  },
  'paragraph-xl-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '34px',
    lineHeight: '36px',
  },
  'paragraph-lg-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '32px',
  },
  'paragraph-md-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '28px',
  },
  'paragraph-sm-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
  },
  'paragraph-xs-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
  },
  'paragraph-xxs-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '16px',
  },

  'paragraph-xxl-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '32px',
    lineHeight: '48px',
  },
  'paragraph-xl-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '34px',
    lineHeight: '36px',
  },
  'paragraph-lg-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '32px',
  },
  'paragraph-md-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '28px',
  },
  'paragraph-sm-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '0.02em',
  },
  'paragraph-xs-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '0.02em',
  },
  'paragraph-xxs-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '0.02em',
  },

  'paragraph-xxl-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '32px',
    lineHeight: '48px',
  },
  'paragraph-xl-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '34px',
    lineHeight: '36px',
  },
  'paragraph-lg-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '20px',
    lineHeight: '32px',
  },
  'paragraph-md-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '18px',
    lineHeight: '28px',
  },
  'paragraph-sm-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '0.02em',
  },
  'paragraph-xs-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '0.02em',
  },
  'paragraph-xxs-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '0.02em',
  },

  'label-xl-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'label-lg-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'label-md-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'label-sm-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'label-xs-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '14px',
    letterSpacing: '0.02em',
  },
  'label-xxs-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '12px',
    letterSpacing: '0.02em',
  },

  'label-xl-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'label-lg-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'label-md-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'label-sm-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'label-xs-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '14px',
    letterSpacing: '0.02em',
  },
  'label-xxs-italic': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '12px',
    letterSpacing: '0.02em',
  },

  'label-xl-medium': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'label-lg-medium': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'label-md-medium': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'label-sm-medium': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'label-xs-medium': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '14px',
    letterSpacing: '0.02em',
  },
  'label-xxs-medium': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '12px',
    lineHeight: '12px',
    letterSpacing: '0.02em',
  },

  'label-xl-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'label-lg-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'label-md-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'label-sm-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'label-xs-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '14px',
    lineHeight: '14px',
    letterSpacing: '0.02em',
  },
  'label-xxs-bold': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '12px',
    lineHeight: '12px',
    letterSpacing: '0.02em',
  },

  'uppercase-xl-default': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'uppercase-lg-default': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'uppercase-md-default': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'uppercase-sm-default': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'uppercase-xs-default': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '14px',
  },
  'uppercase-xxs-default': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '12px',
  },

  'uppercase-xl-italic': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'uppercase-lg-italic': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'uppercase-md-italic': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'uppercase-sm-italic': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'uppercase-xs-italic': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '14px',
  },
  'uppercase-xxs-italic': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '12px',
  },

  'uppercase-xl-medium': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'uppercase-lg-medium': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'uppercase-md-medium': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'uppercase-sm-medium': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'uppercase-xs-medium': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '14px',
  },
  'uppercase-xxs-medium': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '12px',
    lineHeight: '12px',
  },

  'uppercase-xl-bold': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'uppercase-lg-bold': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'uppercase-md-bold': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'uppercase-sm-bold': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'uppercase-xs-bold': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '14px',
    lineHeight: '14px',
  },
  'uppercase-xxs-bold': {
    textTransform: 'upperCase',
    letterSpacing: '0.05em',
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '12px',
    lineHeight: '12px',
  },

  'monospace-xl-default': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'monospace-lg-default': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'monospace-md-default': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'monospace-sm-default': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'monospace-xs-default': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '14px',
    letterSpacing: '0.02em',
  },
  'monospace-xxs-default': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '12px',
  },

  'monospace-xl-italic': {
    fontFamily: 'SF Mono',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'monospace-lg-italic': {
    fontFamily: 'SF Mono',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'monospace-md-italic': {
    fontFamily: 'SF Mono',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'monospace-sm-italic': {
    fontFamily: 'SF Mono',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'monospace-xs-italic': {
    fontFamily: 'SF Mono',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '14px',
  },
  'monospace-xxs-italic': {
    fontFamily: 'SF Mono',
    fontStyle: 'italic',
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '12px',
  },

  'monospace-xl-medium': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'monospace-lg-medium': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'monospace-md-medium': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'monospace-sm-medium': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'monospace-xs-medium': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '14px',
  },
  'monospace-xxs-medium': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '12px',
    lineHeight: '12px',
  },

  'monospace-xl-bold': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '32px',
    lineHeight: '32px',
  },
  'monospace-lg-bold': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '28px',
    lineHeight: '28px',
  },
  'monospace-md-bold': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '20px',
    lineHeight: '20px',
  },
  'monospace-sm-bold': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '18px',
    lineHeight: '18px',
  },
  'monospace-xs-bold': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '14px',
    lineHeight: '14px',
  },
  'monospace-xxs-bold': {
    fontFamily: 'SF Mono',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: '12px',
    lineHeight: '12px',
  },

  'button-default': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '24px',
  },
  'button-uppercase': {
    fontFamily: 'Helvetica Neue',
    fontStyle: 'normal',
    fontWeight: '500',
    fontSize: '18px',
    lineHeight: '18px',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
};

export const Text = {
  baseStyle: { fontStyle: 'Helvetica Neue', fontColor: 'neutrals.900' },
  sizes: sizeText,
};

export default Text;
